### ISSUE TITLE
The Building has the Wrong Name

### ISSUE THREAD

**Issue by nrg294** [joannakl/cs480_s18#46] opened 2018-02-15 00:44 UTC
It says that the building is 

<img width="488" alt="screen shot 2018-02-14 at 7 42 21 pm" src="https://user-images.githubusercontent.com/33606513/36235559-60958baa-11bf-11e8-8abe-3d2b2a4d1fe6.png">

however on Albert it says 60 5th Ave.

**Comment by extra-mayo** [comment] 2018-02-17 14:03
I'd like to claim this issue!

**Comment by joannakl** [comment] 2018-02-17 16:52
duplicate of #10

**Closed as completed by joannakl** 2018-02-17 16:52 UTC
Labels: duplicate
